apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "oai-cu.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "oai-cu.selectorLabels" . | nindent 6 }}

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        {{- include "oai-cu.selectorLabels" . | nindent 8 }}
        app: oai-cu
      {{- if or .Values.multus.f1Interface.create .Values.multus.n2Interface.create .Values.multus.n3Interface.create }}
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
          {{- if .Values.multus.f1Interface.create }}
            { "name": "{{ .Chart.Name }}-f1", "interface": "f1" }{{- if or .Values.multus.n2Interface.create .Values.multus.n3Interface.create }},{{- end }}
          {{- end }}
          {{- if .Values.multus.n3Interface.create }}
            { "name": "{{ .Chart.Name }}-n3", "interface": "n3" }{{- if .Values.multus.n2Interface.create }},{{- end }}
          {{- end }}
          {{- if .Values.multus.n2Interface.create }}
            { "name": "{{ .Chart.Name }}-n2", "interface": "n2" }
          {{- end }}
          ]
      {{- end }}

    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}

      containers:
        - name: gnbcu
          image: "{{ .Values.nfimage.repository }}:{{ .Values.nfimage.version }}"
          securityContext:
            privileged: true

          volumeMounts:
            - mountPath: /opt/oai-gnb/etc
              name: configuration

          {{- if .Values.resources.define }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.nf.memory | quote }}
              cpu: {{ .Values.resources.requests.nf.cpu | quote }}
            limits:
              memory: {{ .Values.resources.limits.nf.memory | quote }}
              cpu: {{ .Values.resources.limits.nf.cpu | quote }}
          {{- end }}

          ports:
            - name: n3
              containerPort: 2152
              protocol: UDP
            - name: n2
              containerPort: 36412
              protocol: SCTP
            - name: f1c
              containerPort: 501
              protocol: SCTP
            - name: f1u
              containerPort: 2152
              protocol: UDP

          {{- if .Values.start.gnbcu }}
          command: ["/bin/bash", "-c"]
          args:
            - |
              AMF_IP_ADDRESS=$(getent hosts $AMF_HOST | awk '{print $1}');
              AMF_IP_ADDRESS=$(if [[ $AMF_IP_ADDRESS ]]; then echo $AMF_IP_ADDRESS; else echo $AMF_HOST; fi);
              N2_IP_ADDRESS=$(ip -f inet addr show $N2_IF_NAME | grep -o "inet [0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | awk '{print $2}' | cut -d/ -f1);
              N3_IP_ADDRESS=$(ip -f inet addr show $N3_IF_NAME | grep -o "inet [0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | awk '{print $2}' | cut -d/ -f1);
              F1_IP_ADDRESS=$(ip -f inet addr show $F1_IF_NAME | grep -o "inet [0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | awk '{print $2}' | cut -d/ -f1);
              sed -e s/@N2_IP_ADDRESS@/$N2_IP_ADDRESS/g \
                  -e s/@N3_IP_ADDRESS@/$N3_IP_ADDRESS/g \
                  -e s/@F1_IP_ADDRESS@/$F1_IP_ADDRESS/g \
                  -e s/@AMF_IP_ADDRESS@/$AMF_IP_ADDRESS/g \
                  /opt/oai-gnb/etc/cu.conf | tee /tmp/cu.conf;
              exec /opt/oai-gnb/bin/nr-softmodem -O /tmp/cu.conf $USE_ADDITIONAL_OPTIONS;
          {{- else }}
          command: ["/bin/sleep", "infinity"]
          {{- end }}

          env:
            - name: DU_HOST
              value: "172.20.1.213"
            - name: TZ
              value: {{ .Values.config.timeZone | quote }}
            - name: USE_ADDITIONAL_OPTIONS
              value: {{ .Values.config.useAdditionalOptions | quote }}
            - name: OAI_GDBSTACKS
              value: "1"
            - name: AMF_HOST
              value: {{ .Values.config.amfhost | quote }}
            - name: N2_IF_NAME
              value: {{ .Values.config.n2IfName | quote }}
            - name: N3_IF_NAME
              value: {{ .Values.config.n3IfName | quote }}
            - name: F1_IF_NAME
              value: {{ .Values.config.f1IfName | quote }}

        {{- if .Values.includeTcpDumpContainer }}
        - name: tcpdump
          image: "{{ .Values.tcpdumpimage.repository }}:{{ .Values.tcpdumpimage.version }}"
          imagePullPolicy: {{ .Values.tcpdumpimage.pullPolicy }}
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
              drop: ["ALL"]

          {{- if .Values.resources.define }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.tcpdump.memory | quote }}
              cpu: {{ .Values.resources.requests.tcpdump.cpu | quote }}
            limits:
              memory: {{ .Values.resources.limits.tcpdump.memory | quote }}
              cpu: {{ .Values.resources.limits.tcpdump.cpu | quote }}
          {{- end }}

          {{- if .Values.start.tcpdump }}
          command: ["/bin/sh", "-c"]
          args:
            - /usr/sbin/tcpdump -i any -w /tmp/pcap/{{ .Chart.Name }}_`date +%Y-%m-%d_%H_%M-%S-%Z`.pcap
          {{- else }}
          command: ["/bin/sleep", "infinity"]
          {{- end }}
        {{- end }}

      volumes:
        - name: configuration
          configMap:
            name: {{ .Chart.Name }}-configmap

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: {{ .Values.serviceAccount.name }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}

      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}

      {{- if .Values.nodeName }}
      nodeName: {{ .Values.nodeName }}
      {{- end }}
