---
# Source: oai-nr-ue-level1/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oai-nr-ue-level1-sa
---
# Source: oai-nr-ue-level1/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6e319
---
# Source: oai-nr-ue-level1/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: oai-nr-ue-level1-configmap
data:
  nr-ue.conf: |
      uicc0 = {
      imsi = "208990100001101";
      key = "a92d71ed92f43ebae1720f34fd2e6966";
      opc= "C42449363BBAD02B66D16BC975D77CC1";
      dnn= "oai";
      nssai_sst="1";
      nssai_sd="FFFFFF";
      }
---
# Source: oai-nr-ue-level1/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-nr-ue-level1
  labels:
    helm.sh/chart: oai-nr-ue-level1-2.0.0
    app.kubernetes.io/name: oai-nr-ue-level1
    app.kubernetes.io/instance: oai-nr-ue-level1
    app.kubernetes.io/version: "develop"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: oai-nr-ue-level1
      app.kubernetes.io/instance: oai-nr-ue-level1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oai-nr-ue-level1
        app.kubernetes.io/instance: oai-nr-ue-level1
        app: oai-nr-ue
      annotations:
        k8s.v1.cni.cncf.io/networks: >-
          [{
                 "name": "oai-nr-ue-level1-net1"
          }]
    spec:
      securityContext:
        runAsGroup: 0
        runAsUser: 0
      imagePullSecrets:
        - name: regcred
      containers:
      - name: nr-ue
        image: "docker.io/oaisoftwarealliance/oai-nr-ue:2023.w49"
        volumeMounts:
          - mountPath: /opt/oai-nr-ue/etc
            name: configuration
            # subPath: gnb.conf
          # USRP B210/B200 Mini
        securityContext:
           privileged: true
        command: [ "/bin/bash", "-c" ]
        args:
          - RFSIM_IP_ADDRESS=$(getent hosts $RFSIM_HOST | awk '{print $1}');
            RFSIM_IP_ADDRESS=$(if [[ $RFSIM_IP_ADDRESS ]]; then echo $RFSIM_IP_ADDRESS; else echo $RFSIM_HOST;fi);
              exec /opt/oai-nr-ue/bin/nr-uesoftmodem -O /opt/oai-nr-ue/etc/nr-ue.conf $USE_ADDITIONAL_OPTIONS --rfsimulator.serveraddr $RFSIM_IP_ADDRESS;
        env:
          - name: TZ
            value: UTC
          - name: RFSIM_HOST
            value: 172.20.1.213
          - name: USE_ADDITIONAL_OPTIONS
            value: --sa --rfsim -r 106 --numerology 1 -C 3619200000 --nokrnmod --log_config.global_log_options level,nocolor,time
      volumes:
      - configMap:
          name: oai-nr-ue-level1-configmap
        name: configuration
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: 
      terminationGracePeriodSeconds: 0
      nodeName: awanbaru
---
# Source: oai-nr-ue-level1/templates/multus.yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: oai-nr-ue-level1-net1
spec:
  config: '{ 
      "cniVersion": "0.3.1",
      "type": "ipvlan",
      "master":"eth0",
      "mode": "l2",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address":"172.20.1.214/24"
                }
        ]
      }
    }'
